// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlF8EPjs5UXWTl5-s-d6SiBjLB5WgBZv8',
    appId: '1:668235728899:web:959f104b656a722e2e2636',
    messagingSenderId: '668235728899',
    projectId: 'syrus-hackathon',
    authDomain: 'syrus-hackathon.firebaseapp.com',
    storageBucket: 'syrus-hackathon.appspot.com',
    measurementId: 'G-52H4RYR41C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb6_7GaZeEKl_ZaHgTfjlJLcukGsnSvWI',
    appId: '1:668235728899:android:508b15a6b39375752e2636',
    messagingSenderId: '668235728899',
    projectId: 'syrus-hackathon',
    storageBucket: 'syrus-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAGuxe8J-9JCWSQTEAwOrPbJvDti3wTw4',
    appId: '1:668235728899:ios:220de9754d5a59612e2636',
    messagingSenderId: '668235728899',
    projectId: 'syrus-hackathon',
    storageBucket: 'syrus-hackathon.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAGuxe8J-9JCWSQTEAwOrPbJvDti3wTw4',
    appId: '1:668235728899:ios:07176efd3a0da0822e2636',
    messagingSenderId: '668235728899',
    projectId: 'syrus-hackathon',
    storageBucket: 'syrus-hackathon.appspot.com',
    iosBundleId: 'com.example.hackathon.RunnerTests',
  );
}